/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package graphics;

import scenarioresults.FifthScenario;
import scenarioresults.FirstScenario;
import scenarioresults.FourthScenario;
import scenarioresults.SecondScenario;
import scenarioresults.ShowValues;
import scenarioresults.ThirdScenario;

/**
 *
 * @author irvingjose
 */
public class MainInterface extends javax.swing.JFrame {

    /**
     * Creates new form MainInterface
     */
    public MainInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        panelbuttons = new javax.swing.JPanel();
        panelfirst = new javax.swing.JPanel();
        firstscenario = new javax.swing.JLabel();
        panelsecond = new javax.swing.JPanel();
        secondscenario = new javax.swing.JLabel();
        panelthird = new javax.swing.JPanel();
        thirdscenario = new javax.swing.JLabel();
        panelfourth = new javax.swing.JPanel();
        fourthscenario = new javax.swing.JLabel();
        panelfifth = new javax.swing.JPanel();
        fifthscenario = new javax.swing.JLabel();
        panelpresentation = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        subtitle = new javax.swing.JLabel();
        text1 = new javax.swing.JLabel();
        text2 = new javax.swing.JLabel();
        text3 = new javax.swing.JLabel();
        text4 = new javax.swing.JLabel();
        text5 = new javax.swing.JLabel();
        text6 = new javax.swing.JLabel();
        panelallvariables = new javax.swing.JPanel();
        buttonallvariables = new javax.swing.JLabel();
        panelvalues = new javax.swing.JPanel();
        buttonvaluescurrent = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 254));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelbuttons.setBackground(new java.awt.Color(230, 235, 224));
        panelbuttons.setPreferredSize(new java.awt.Dimension(150, 250));

        panelfirst.setBackground(new java.awt.Color(0, 134, 190));

        firstscenario.setFont(new java.awt.Font("PT Sans", 3, 14)); // NOI18N
        firstscenario.setForeground(new java.awt.Color(255, 255, 255));
        firstscenario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstscenario.setText("First Scenario");
        firstscenario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        firstscenario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstscenarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelfirstLayout = new javax.swing.GroupLayout(panelfirst);
        panelfirst.setLayout(panelfirstLayout);
        panelfirstLayout.setHorizontalGroup(
            panelfirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelfirstLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(firstscenario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelfirstLayout.setVerticalGroup(
            panelfirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelfirstLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(firstscenario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelsecond.setBackground(new java.awt.Color(0, 134, 190));

        secondscenario.setFont(new java.awt.Font("PT Sans", 3, 14)); // NOI18N
        secondscenario.setForeground(new java.awt.Color(255, 255, 255));
        secondscenario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        secondscenario.setText("Second Scenario");
        secondscenario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        secondscenario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                secondscenarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelsecondLayout = new javax.swing.GroupLayout(panelsecond);
        panelsecond.setLayout(panelsecondLayout);
        panelsecondLayout.setHorizontalGroup(
            panelsecondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsecondLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(secondscenario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelsecondLayout.setVerticalGroup(
            panelsecondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelsecondLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(secondscenario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelthird.setBackground(new java.awt.Color(0, 134, 190));

        thirdscenario.setFont(new java.awt.Font("PT Sans", 3, 14)); // NOI18N
        thirdscenario.setForeground(new java.awt.Color(255, 255, 255));
        thirdscenario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thirdscenario.setText("Third Scenario");
        thirdscenario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        thirdscenario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thirdscenarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelthirdLayout = new javax.swing.GroupLayout(panelthird);
        panelthird.setLayout(panelthirdLayout);
        panelthirdLayout.setHorizontalGroup(
            panelthirdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelthirdLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(thirdscenario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelthirdLayout.setVerticalGroup(
            panelthirdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelthirdLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(thirdscenario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelfourth.setBackground(new java.awt.Color(0, 134, 190));

        fourthscenario.setFont(new java.awt.Font("PT Sans", 3, 14)); // NOI18N
        fourthscenario.setForeground(new java.awt.Color(255, 255, 255));
        fourthscenario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fourthscenario.setText("Fourth Scenario");
        fourthscenario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fourthscenario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fourthscenarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelfourthLayout = new javax.swing.GroupLayout(panelfourth);
        panelfourth.setLayout(panelfourthLayout);
        panelfourthLayout.setHorizontalGroup(
            panelfourthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfourthLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fourthscenario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelfourthLayout.setVerticalGroup(
            panelfourthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelfourthLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fourthscenario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelfifth.setBackground(new java.awt.Color(0, 134, 190));

        fifthscenario.setFont(new java.awt.Font("PT Sans", 3, 14)); // NOI18N
        fifthscenario.setForeground(new java.awt.Color(255, 255, 255));
        fifthscenario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fifthscenario.setText("Fifth Scenario");
        fifthscenario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fifthscenario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fifthscenarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelfifthLayout = new javax.swing.GroupLayout(panelfifth);
        panelfifth.setLayout(panelfifthLayout);
        panelfifthLayout.setHorizontalGroup(
            panelfifthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfifthLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fifthscenario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelfifthLayout.setVerticalGroup(
            panelfifthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelfifthLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fifthscenario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelbuttonsLayout = new javax.swing.GroupLayout(panelbuttons);
        panelbuttons.setLayout(panelbuttonsLayout);
        panelbuttonsLayout.setHorizontalGroup(
            panelbuttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbuttonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelbuttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelfirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelsecond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelthird, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelfourth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelfifth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelbuttonsLayout.setVerticalGroup(
            panelbuttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbuttonsLayout.createSequentialGroup()
                .addComponent(panelfirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelsecond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelthird, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelfourth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelfifth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        bg.add(panelbuttons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 75, 150, 250));

        panelpresentation.setBackground(new java.awt.Color(230, 235, 224));
        panelpresentation.setPreferredSize(new java.awt.Dimension(500, 50));

        title.setFont(new java.awt.Font("PT Sans", 3, 24)); // NOI18N
        title.setText("Simulacion de Escases de Agua");

        subtitle.setFont(new java.awt.Font("PT Sans", 3, 14)); // NOI18N
        subtitle.setText("Oaxaca de Juarez - Zona Metropolitana de Oaxaca");

        javax.swing.GroupLayout panelpresentationLayout = new javax.swing.GroupLayout(panelpresentation);
        panelpresentation.setLayout(panelpresentationLayout);
        panelpresentationLayout.setHorizontalGroup(
            panelpresentationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpresentationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelpresentationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtitle))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        panelpresentationLayout.setVerticalGroup(
            panelpresentationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpresentationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtitle)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        bg.add(panelpresentation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 75));

        text1.setText("Modelo de Dinámica de Sistemas (SD)");
        bg.add(text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        text2.setText("Evaluación de la sostenibilidad hídrica a 100 años");
        text2.setPreferredSize(new java.awt.Dimension(322, 20));
        bg.add(text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        text3.setText("bajo diferentes políticas.");
        bg.add(text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        text4.setText("A continuacion se muestran 5 escenarios diseñados");
        text4.setPreferredSize(new java.awt.Dimension(330, 20));
        bg.add(text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        text5.setText("con 5 variables clave de sensibilidad y un escenario");
        text5.setPreferredSize(new java.awt.Dimension(330, 15));
        bg.add(text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        text6.setText("optimo con todas las variables.");
        text6.setPreferredSize(new java.awt.Dimension(230, 15));
        bg.add(text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 185, -1, -1));

        panelallvariables.setBackground(new java.awt.Color(0, 134, 190));

        buttonallvariables.setForeground(new java.awt.Color(255, 255, 255));
        buttonallvariables.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonallvariables.setText("Optimalidad de todas las variables ");
        buttonallvariables.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelallvariablesLayout = new javax.swing.GroupLayout(panelallvariables);
        panelallvariables.setLayout(panelallvariablesLayout);
        panelallvariablesLayout.setHorizontalGroup(
            panelallvariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonallvariables, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelallvariablesLayout.setVerticalGroup(
            panelallvariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelallvariablesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonallvariables, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(panelallvariables, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 220, 35));

        panelvalues.setBackground(new java.awt.Color(0, 134, 190));

        buttonvaluescurrent.setForeground(new java.awt.Color(255, 255, 255));
        buttonvaluescurrent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonvaluescurrent.setText("Mostar valores");
        buttonvaluescurrent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonvaluescurrent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonvaluescurrentMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelvaluesLayout = new javax.swing.GroupLayout(panelvalues);
        panelvalues.setLayout(panelvaluesLayout);
        panelvaluesLayout.setHorizontalGroup(
            panelvaluesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonvaluescurrent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        panelvaluesLayout.setVerticalGroup(
            panelvaluesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonvaluescurrent, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        bg.add(panelvalues, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 260, 140, 35));

        jLabel1.setText("Destacar que las gráficas en azul representan los");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 205, 330, 15));

        jLabel2.setText("valores actuales, mientras que las gráficas en rojo");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 330, 15));

        jLabel3.setText("los valores óptimos.");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 235, 330, 15));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void firstscenarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstscenarioMouseClicked
        FirstScenario scenary = new FirstScenario();
        scenary.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_firstscenarioMouseClicked

    private void secondscenarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_secondscenarioMouseClicked
        SecondScenario scenary = new SecondScenario();
        scenary.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_secondscenarioMouseClicked

    private void buttonvaluescurrentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonvaluescurrentMouseClicked
        ShowValues mostrarvalores = new ShowValues();
        mostrarvalores.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonvaluescurrentMouseClicked

    private void thirdscenarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thirdscenarioMouseClicked
        ThirdScenario scenary = new ThirdScenario();
        scenary.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_thirdscenarioMouseClicked

    private void fourthscenarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourthscenarioMouseClicked
        FourthScenario scenary = new FourthScenario();
        scenary.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_fourthscenarioMouseClicked

    private void fifthscenarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fifthscenarioMouseClicked
        FifthScenario scenary = new FifthScenario();
        scenary.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_fifthscenarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInterface().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel buttonallvariables;
    private javax.swing.JLabel buttonvaluescurrent;
    private javax.swing.JLabel fifthscenario;
    private javax.swing.JLabel firstscenario;
    private javax.swing.JLabel fourthscenario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panelallvariables;
    private javax.swing.JPanel panelbuttons;
    private javax.swing.JPanel panelfifth;
    private javax.swing.JPanel panelfirst;
    private javax.swing.JPanel panelfourth;
    private javax.swing.JPanel panelpresentation;
    private javax.swing.JPanel panelsecond;
    private javax.swing.JPanel panelthird;
    private javax.swing.JPanel panelvalues;
    private javax.swing.JLabel secondscenario;
    private javax.swing.JLabel subtitle;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel text3;
    private javax.swing.JLabel text4;
    private javax.swing.JLabel text5;
    private javax.swing.JLabel text6;
    private javax.swing.JLabel thirdscenario;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
