/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package scenarioresults;

import graphics.MainInterface;
import scenarios.Scenary2;

/**
 *
 * @author irvingjose
 */
public class SecondScenario extends javax.swing.JFrame {

    /**
     * Creates new form SecondScenario
     */
    public SecondScenario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gb = new javax.swing.JPanel();
        tittle = new javax.swing.JLabel();
        text1 = new javax.swing.JLabel();
        text2 = new javax.swing.JLabel();
        text4 = new javax.swing.JLabel();
        text5 = new javax.swing.JLabel();
        text6 = new javax.swing.JLabel();
        panelsimulation = new javax.swing.JPanel();
        simulation = new javax.swing.JLabel();
        panelreturns = new javax.swing.JPanel();
        returns = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        gb.setBackground(new java.awt.Color(244, 241, 187));
        gb.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tittle.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittle.setText("Resultados obtenidos en el segundo escenario");
        gb.add(tittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, -1));

        text1.setText("Se muestra el impacto del consumo de agua no potable por");
        gb.add(text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 380, 15));

        text2.setText("persona (NWCP) óptimo.");
        gb.add(text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, 380, 15));

        text4.setText("Consumo de agua no potable por persona (NWCP) toma el");
        gb.add(text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 380, 15));

        text5.setText("valor óptimo de 110 m³/presona×año de acuerdo a los");
        gb.add(text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 105, 380, 15));

        text6.setText("datos de simulación.");
        gb.add(text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 380, 15));

        panelsimulation.setBackground(new java.awt.Color(0, 134, 190));

        simulation.setFont(new java.awt.Font("PT Sans", 3, 14)); // NOI18N
        simulation.setForeground(new java.awt.Color(255, 255, 255));
        simulation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        simulation.setText("Simulacion");
        simulation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simulation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simulationMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelsimulationLayout = new javax.swing.GroupLayout(panelsimulation);
        panelsimulation.setLayout(panelsimulationLayout);
        panelsimulationLayout.setHorizontalGroup(
            panelsimulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsimulationLayout.createSequentialGroup()
                .addComponent(simulation, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelsimulationLayout.setVerticalGroup(
            panelsimulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsimulationLayout.createSequentialGroup()
                .addComponent(simulation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        gb.add(panelsimulation, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 180, 125, 30));

        panelreturns.setBackground(new java.awt.Color(0, 134, 190));

        returns.setFont(new java.awt.Font("PT Sans", 3, 14)); // NOI18N
        returns.setForeground(new java.awt.Color(255, 255, 255));
        returns.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        returns.setText("Regresar");
        returns.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelreturnsLayout = new javax.swing.GroupLayout(panelreturns);
        panelreturns.setLayout(panelreturnsLayout);
        panelreturnsLayout.setHorizontalGroup(
            panelreturnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelreturnsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(returns, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelreturnsLayout.setVerticalGroup(
            panelreturnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelreturnsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(returns, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gb.add(panelreturns, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 125, 30));
        gb.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 50, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void simulationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simulationMouseClicked
        Scenary2 scenario = new Scenary2();
        scenario.run();
        this.dispose();
    }//GEN-LAST:event_simulationMouseClicked

    private void returnsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnsMouseClicked
        MainInterface mi = new MainInterface();
        mi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecondScenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecondScenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecondScenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecondScenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecondScenario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel gb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelreturns;
    private javax.swing.JPanel panelsimulation;
    private javax.swing.JLabel returns;
    private javax.swing.JLabel simulation;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel text4;
    private javax.swing.JLabel text5;
    private javax.swing.JLabel text6;
    private javax.swing.JLabel tittle;
    // End of variables declaration//GEN-END:variables
}
