/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package scenarioresults;

import graphics.MainInterface;
import java.text.DecimalFormat;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Parameters;

/**
 *
 * @author irvingjose
 */
public class ShowValues extends javax.swing.JFrame {
    private static final DecimalFormat formatter = new DecimalFormat("#,###");
    
    /**
     * Creates new form ShowCurrentValues
     */
    public ShowValues() {
        initComponents();
        table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelprincipal = new javax.swing.JPanel();
        tittle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        valores = new javax.swing.JTable();
        panelreturns = new javax.swing.JPanel();
        returns = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panelprincipal.setBackground(new java.awt.Color(244, 241, 187));
        panelprincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tittle.setFont(new java.awt.Font("PT Sans", 3, 20)); // NOI18N
        tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittle.setText("Valores actuales y optimos");
        panelprincipal.add(tittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 540, -1));

        valores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Variable", "Unidad", "Valor Actual", "Valor Optimo"
            }
        ));
        valores.setSize(new java.awt.Dimension(360, 80));
        jScrollPane1.setViewportView(valores);

        panelprincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 500, 160));

        panelreturns.setBackground(new java.awt.Color(0, 134, 190));

        returns.setFont(new java.awt.Font("PT Sans", 3, 14)); // NOI18N
        returns.setForeground(new java.awt.Color(255, 255, 255));
        returns.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        returns.setText("Regresar");
        returns.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelreturnsLayout = new javax.swing.GroupLayout(panelreturns);
        panelreturns.setLayout(panelreturnsLayout);
        panelreturnsLayout.setHorizontalGroup(
            panelreturnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelreturnsLayout.createSequentialGroup()
                .addComponent(returns, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelreturnsLayout.setVerticalGroup(
            panelreturnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelreturnsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(returns, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelprincipal.add(panelreturns, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 300, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void returnsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnsMouseClicked
        MainInterface mi = new MainInterface();
        mi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnsMouseClicked

    public void table() {

    // 1. Nombres de columnas
    String[] columnNames = {"Variable", "Unidad", "Valor Actual", "Valor Óptimo"};

    // 2. Datos de la tabla ya formateados
    Object[][] data = {
        {"Población (POP)", "personas",
            formatter.format(Parameters.POP_INITIAL), "---"},
        
        {"Suscriptores (ISS)", "suscriptores",
            formatter.format(Parameters.ISS_INITIAL), "-"},
        
        {"Penetracion (PR)", "m³/año",
            formatter.format(Parameters.PR),
            formatter.format(Parameters.PR * 1.10)},
        
        {"Consumo No Potable (NWCP)", "m³/persona-año",
            formatter.format(Parameters.NWCP),
            formatter.format(110)},
        
        {"Consumo Industrial (ISWCP)", "m³/suscriptor-año",
            formatter.format(Parameters.ISWCP),
            formatter.format(390)},
        
        {"Nacimientos (BR)", "personas/año",
            formatter.format(Parameters.BR),
            formatter.format(4485)},
        
        {"Defunciones (DR)", "personas/año",
            formatter.format(Parameters.DR), "---"},
        
        {"Nuevos suscriptores (NSR)", "suscriptores/año",
            formatter.format(Parameters.NSR),
            formatter.format(708)},
    };

    // 3. Modelo de tabla
    DefaultTableModel tableModel = new DefaultTableModel(data, columnNames) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // No editable
        }
    };

    // 4. Aplicar modelo al JTable
    valores.setModel(tableModel);

    // 5. Permitir redimensionar columnas
    valores.getTableHeader().setResizingAllowed(true);

    // 6. Ajustar ancho inicial de columnas
    valores.getColumnModel().getColumn(0).setPreferredWidth(180); // Variable
    valores.getColumnModel().getColumn(1).setPreferredWidth(120);  // Unidad
    valores.getColumnModel().getColumn(2).setPreferredWidth(100); // Valor actual
    valores.getColumnModel().getColumn(3).setPreferredWidth(100); // Valor óptimo
}


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowValues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowValues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowValues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowValues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowValues().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelprincipal;
    private javax.swing.JPanel panelreturns;
    private javax.swing.JLabel returns;
    private javax.swing.JLabel tittle;
    private javax.swing.JTable valores;
    // End of variables declaration//GEN-END:variables
}
