/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interpretations;

import scenarios.Scenary4;

/**
 *
 * @author 52951
 */
public class Interpretacion4 extends javax.swing.JFrame {

    /**
     * Creates new form interpretacion4
     */
    public Interpretacion4() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gb = new javax.swing.JPanel();
        tittle = new javax.swing.JLabel();
        text1 = new javax.swing.JLabel();
        text2 = new javax.swing.JLabel();
        text3 = new javax.swing.JLabel();
        text4 = new javax.swing.JLabel();
        text5 = new javax.swing.JLabel();
        text7 = new javax.swing.JLabel();
        text8 = new javax.swing.JLabel();
        text9 = new javax.swing.JLabel();
        panelsimulation = new javax.swing.JPanel();
        simulation = new javax.swing.JLabel();
        esp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        gb.setBackground(new java.awt.Color(244, 241, 187));
        gb.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tittle.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittle.setText("Interpretación Cuarto Escenario");
        gb.add(tittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 430, -1));

        text1.setText("En este escenario, al modificar la variable BR (natalidad), las gráficas");
        gb.add(text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 390, 15));

        text2.setText("muestran que el cambio tiene un efecto pequeño pero visible. La línea");
        gb.add(text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 65, 390, 15));

        text3.setText("roja del agua disponible (AW) se mantiene ligeramente por encima de ");
        gb.add(text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 390, 15));

        text4.setText("la azul, lo que indica que un menor crecimiento poblacional reduce un");
        gb.add(text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 95, 390, 15));

        text5.setText("poco la demanda de agua y permite conservar más recurso a lo");
        gb.add(text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 390, 15));

        text7.setText("largo del tiempo.");
        gb.add(text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 125, 390, 20));

        text8.setText("En el balance hídrico (WB) también se nota una mejora moderada.");
        gb.add(text8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 165, 390, 15));

        text9.setText("Aunque ambas líneas siguen descendiendo, la roja baja un poco más");
        gb.add(text9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 390, 15));

        panelsimulation.setBackground(new java.awt.Color(0, 134, 190));

        simulation.setFont(new java.awt.Font("PT Sans", 3, 14)); // NOI18N
        simulation.setForeground(new java.awt.Color(255, 255, 255));
        simulation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        simulation.setText("Simulacion");
        simulation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simulation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simulationMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelsimulationLayout = new javax.swing.GroupLayout(panelsimulation);
        panelsimulation.setLayout(panelsimulationLayout);
        panelsimulationLayout.setHorizontalGroup(
            panelsimulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelsimulationLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(simulation, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelsimulationLayout.setVerticalGroup(
            panelsimulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelsimulationLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(simulation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gb.add(panelsimulation, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 130, 30));
        gb.add(esp, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 285, 30, 15));

        jLabel1.setText(" despacio, mostrando que el déficit de agua crece a un ritmo menor.");
        gb.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simulationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simulationMouseClicked
        Scenary4 scenario = new Scenary4();
        scenario.run();
        this.dispose();
    }//GEN-LAST:event_simulationMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interpretacion4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interpretacion4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interpretacion4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interpretacion4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interpretacion4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel esp;
    private javax.swing.JPanel gb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelsimulation;
    private javax.swing.JLabel simulation;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel text3;
    private javax.swing.JLabel text4;
    private javax.swing.JLabel text5;
    private javax.swing.JLabel text7;
    private javax.swing.JLabel text8;
    private javax.swing.JLabel text9;
    private javax.swing.JLabel tittle;
    // End of variables declaration//GEN-END:variables
}
