/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interpretations;

import scenarios.Scenary3;

/**
 *
 * @author 52951
 */
public class Interpretacion3 extends javax.swing.JFrame {

    /**
     * Creates new form interpretacion3
     */
    public Interpretacion3() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gb = new javax.swing.JPanel();
        tittle = new javax.swing.JLabel();
        text1 = new javax.swing.JLabel();
        text2 = new javax.swing.JLabel();
        text3 = new javax.swing.JLabel();
        text4 = new javax.swing.JLabel();
        text5 = new javax.swing.JLabel();
        text6 = new javax.swing.JLabel();
        text7 = new javax.swing.JLabel();
        text8 = new javax.swing.JLabel();
        text9 = new javax.swing.JLabel();
        panelsimulation = new javax.swing.JPanel();
        simulation = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        esp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        gb.setBackground(new java.awt.Color(244, 241, 187));
        gb.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tittle.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittle.setText("Interpretación Tercer Escenario");
        gb.add(tittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 430, -1));

        text1.setText("En este escenario, al modificar la variable ISWCP, las gráficas muestran ");
        gb.add(text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 390, 15));

        text2.setText("que las mejoras son mínimas. La línea roja (escenario óptimo) se mantiene");
        gb.add(text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 65, 390, 15));

        text3.setText("casi igual a la azul, lo que indica que el cambio apenas afecta la cantidad");
        gb.add(text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 390, 15));

        text4.setText("de agua disponible (AW) con el paso de los años.");
        gb.add(text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 95, 390, 15));

        text5.setText("En el balance hídrico (WB) también se observa una diferencia muy ligera: ");
        gb.add(text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 390, 15));

        text6.setText("la línea roja baja un poco más lento, pero la brecha entre ambos");
        gb.add(text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 135, 390, 15));

        text7.setText(" escenarios es muy pequeña.");
        gb.add(text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 390, 15));

        text8.setText("Este escenario muestra que la variable ISWCP tiene un impacto muy");
        gb.add(text8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 165, 390, 15));

        text9.setText("bajo, ya que solo genera mejoras pequeñas tanto en el agua disponible");
        gb.add(text9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 390, 15));

        panelsimulation.setBackground(new java.awt.Color(0, 134, 190));

        simulation.setFont(new java.awt.Font("PT Sans", 3, 14)); // NOI18N
        simulation.setForeground(new java.awt.Color(255, 255, 255));
        simulation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        simulation.setText("Simulacion");
        simulation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simulation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simulationMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelsimulationLayout = new javax.swing.GroupLayout(panelsimulation);
        panelsimulation.setLayout(panelsimulationLayout);
        panelsimulationLayout.setHorizontalGroup(
            panelsimulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelsimulationLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(simulation, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelsimulationLayout.setVerticalGroup(
            panelsimulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelsimulationLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(simulation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gb.add(panelsimulation, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 130, 30));

        jLabel1.setText("como en el balance hídrico.");
        jLabel1.setMaximumSize(new java.awt.Dimension(377, 16));
        jLabel1.setMinimumSize(new java.awt.Dimension(377, 16));
        jLabel1.setPreferredSize(new java.awt.Dimension(377, 16));
        gb.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 380, 15));
        gb.add(esp, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 285, 30, 15));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simulationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simulationMouseClicked
         Scenary3 scenario = new Scenary3();
        scenario.run();
        this.dispose();
    }//GEN-LAST:event_simulationMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interpretacion3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interpretacion3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interpretacion3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interpretacion3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interpretacion3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel esp;
    private javax.swing.JPanel gb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelsimulation;
    private javax.swing.JLabel simulation;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel text3;
    private javax.swing.JLabel text4;
    private javax.swing.JLabel text5;
    private javax.swing.JLabel text6;
    private javax.swing.JLabel text7;
    private javax.swing.JLabel text8;
    private javax.swing.JLabel text9;
    private javax.swing.JLabel tittle;
    // End of variables declaration//GEN-END:variables
}
